<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Bolsa de Trabajo UEH</title>
        <!-- Favicon -->
         <link rel="apple-touch-icon" sizes="57x57" href="../../img/favicon/apple-icon-57x57.png">
        <link rel="apple-touch-icon" sizes="60x60" href="../../img/favicon/apple-icon-60x60.png">
        <link rel="apple-touch-icon" sizes="72x72" href="../../img/favicon/apple-icon-72x72.png">
        <link rel="apple-touch-icon" sizes="76x76" href="../../img/favicon/apple-icon-76x76.png">
        <link rel="apple-touch-icon" sizes="114x114" href="../../img/favicon/apple-icon-114x114.png">
        <link rel="apple-touch-icon" sizes="120x120" href="../../img/favicon/apple-icon-120x120.png">
        <link rel="apple-touch-icon" sizes="144x144" href="../../img/favicon/apple-icon-144x144.png">
        <link rel="apple-touch-icon" sizes="152x152" href="../../img/favicon/apple-icon-152x152.png">
        <link rel="apple-touch-icon" sizes="180x180" href="../../img/favicon/apple-icon-180x180.png">
        <link rel="icon" type="image/png" sizes="192x192"  href="../../img/favicon/android-icon-192x192.png">
        <link rel="icon" type="image/png" sizes="32x32" href="../../img/favicon/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="96x96" href="../../img/favicon/favicon-96x96.png">
        <link rel="icon" type="image/png" sizes="16x16" href="../../img/favicon/favicon-16x16.png">
        <link rel="manifest" href="/manifest.json">
        <meta name="msapplication-TileColor" content="#ffffff">
        <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
        <meta name="theme-color" content="#ffffff">
        <!-- Fin de favicon -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <script src="https://use.fontawesome.com/a707b00bb2.js"></script>

        <link rel="stylesheet" type="text/css" href="../../css/bootstrap-datetimepicker.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.11.2/css/bootstrap-select.min.css">

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">

        <link rel="stylesheet" type="text/css" href="../../css/perfil_egresado_impresion.css" media="print">
        <script src="../../js/sweetalert.min.js"></script>
        <link rel="stylesheet" href="../../css/sweetalert.css">
         <!-- Estilos personales -->
        <link rel="stylesheet" type="text/css" href="../../css/main_egresado.css" media="screen">

    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
<div id="cabecera">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                  <img id="escudo" class="img-responsive center-block" src="../../img/escudo.png">
                  <h2 id="titulo_bolsa_ueh">BOLSA DE TRABAJO UEH</h2>    
            </div>
        </div>
    </div>
</div>
<div id="menu" id="menu-contenedor">
<div class="container" id="divmenu">
    <div class="row" >
        <div class="col-xs-1"></div>
        <div id="btn-inicio" class="menu-item col-xs-2 text-right"><a href="index.php"><p>Inicio</p></a></div>
        <div id="btn-perfil" class="menu-item col-xs-2 text-right"><a href="perfil_egresado.php"><p>Perfil</p></a></div>
        <div class="col-xs-2"><img id="logo-menu" class="img-responsive center-block" src="../../img/escudoN.png"></div>
        <div id="btn-mis-ofertas" class="menu-item col-xs-2"><a href="mis_ofertas.php"><p>Mis ofertas</p></a></div>
        <div id="btn-salir" class="menu-item col-xs-2"><a href="salir.php"><p>Salir</p></a></div>
        <div class="col-xs-1"></div>
    </div>
</div>
</div>